language: go

env:
 - GOOS=linux GOARCH=amd64
 - GOOS=darwin GOARCH=amd64
 - GOOS=windows GOARCH=amd64

deploy:
  provider: releases
  api_key:
    secure: QXXzmYECNj059cmvLbBTnjlNpIwJhbXlppmlmwpknz2/LBLWJiL4xUHVz61if06TmhPJwakxVwN+JqPsD3rWERpdo63foelvduEflO6Gdx8eEwbmMA3nWNXwy8mllBkq7vy1dYdP1x/SmW6o1Q8PuwgqQa+QArV5GI5k6KxF4oo1tRwiZQ58gr11DliQ0pUmSa8qYsaEppD6YOoEIztjVLKAGh/2i0o2r8pVLIT7dkbuEoTfhtxgLYxP9rIdv/g6nyQz6BVQAcPj3gMkgKfHfR8d1T7YTXYHt9mPhwW+a1HO5tzkXfkPQWElG/zyl2/UzUJMPsS6vl5lmw/zcPozT1SYCyuArp1bh14FMmuEI4t1W97NwDVHl9RdAI7zfssQKtWcJvSZR+lyO6Mau6GY69PmUMKoQTluwFrBFpf0SCYzhYUfqlq3USR2BPj8Dg1uDDEo7HfvsoqgNYR4rn55dEdzuuYGSPJM47hedvLwpRupXHoGvmn3cjU54cP2vDQAWptQXbT7S9nGvK+1M9E9U7RIa5eeIb3MM8PYycEq9ySy37+Wx8xpXQP5dATcjkZEoYC7u2w3nn7pHDDXoeLzIN8ad4SrO7mYMVdSQaCEdYPiiasSKpx2zWjEe4PlV2tSSuU0c4LUl3PHsfp3zCOKndaFwSaWXW1EnOU7/UAvzdI=
  file_glob: true
  file: kenney2json.*
  overwrite: true
  skip_cleanup: true
  prerelease: true
  on:
   tags: true


