language: go
env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin
    - BUILD_GOOS=windows

script: 
- env GOOS=$BUILD_GOOS GOARCH=$BUILD_GOARCH go build
- if [[ "$BUILD_GOOS" == "windows" ]]; then zip "kenney2xygine-$BUILD_GOOS" kenney2xygine.exe; fi
- if [[ "$BUILD_GOOS" != "windows" ]]; then zip "kenney2xygine-$BUILD_GOOS" kenney2xygine; fi

deploy:
  provider: releases
  api_key:
    secure: N2OhIZBrB7YYBAY6M3S1Vq5HXd5rk1HcDNinJEaHQ03huHrOrwNvJAA0EKgpdl/jPuTTw+fJOgK+vRYgIZt2oafs5s/GxaUZEZuXEnntrQtXLgoqveFC84UYURQackZ3T99fR7/ewDIw1qdOWK6qPwsw/KyKtMr5y5xaFN+NjzRAs+7NbDYbW5ZnJ1LUTZE0Txlw0VEmzjJZpC+Lhi0sDdYIYL20YTTbDRfhNISU5MRjE1yrMx6UILGAXhLai28OlpTwcAvFTIio8rLpVCVcPkSORqnC7JZtOr9Tr0ZumusB1GUJDbUTUtbCOqrbDpZypGzt8DqW8S/mjCNieukJXaCzPctC9OZp5iLPk8HyLG1FgqazsdIBE8+LxP3zwAejak1UaBV8yatWQ6pf80QIy1hsjE0BE3ECcPIpNZXzS594ARZwbMwtuv0QHoeVmnfmjbbRK6NDHDYt/vzdfHrtPflok5/J7M1v7nEii3dbYZXPFvoE4kwHAC4b8Czg55W9d1yrb6/KNgtg8IUz5+eEZguf4fYGu+Sa8K/X57Pky3rYtIkaEoRsYZn+Hm84P1yKHQp4wBSR7a0TrpY+dzObvVRpFUuldJVjWwSnDAAUcaYgBCpG+J6b6Ym0f7p1FpLGgSB+IcixzXhXT0Wsm6QkwIJoRuDjrdh3JlCy8pP++bM=
  file: kenney2xygine-$BUILD_GOOS.zip
  on:
    repo: JonnyPtn/kenney2xygine
    tags: true
  overwrite: true
  skip_cleanup: true
  prerelease: true